### ISSUE TITLE
Show "units" and "description" sourced from device database

### ISSUE THREAD

**Issue by cnlklink** [fermi-ad/parameter_page_app#18]

**Comment by rneswold** [comment]
Oops. That previous post didn't reveal the real problem.

The real problem is the gRPC protocol to DPM doesn't have any device info -- just reading info. When I faked the data, the app had something to display.

I'm working on getting device data into the resolver. But for now it returns nothing, so we won't see the description or units.

**Comment by rneswold** [comment]
#51 partially fulfilled this issue. There's still a few details to go:

- Devices don't necessarily have both reading an setting properties, so the columns need to be conditionally filled in.
- There are some error conditions that aren't being handled gracefully.

**Comment by cnlklink** [comment]
I'm noticing that descriptions and units are not being returned by the API at the moment.  So I assume this issue is still active?  I dove into the code a bit and it appears that _convertToDevInfo will return a default DeviceInfo object with a blank description and null reading/setting properties if the type of data returned is not recognized.  I think that's the root of the problem.

**Comment by rneswold** [comment]
The `devdb` service was moved to the K8s cluster. I need to update the proxy to point to it instead of CLX76.

**Comment by cnlklink** [comment]
I noticed that after a long wait (maybe 60-120 seconds?) the request eventually timesout and returns an ErrorReply.  I'm going to catch this and have the widget display an error to the user.  But we should probably reduce that timeout to something more responsive, 5-10 seconds perhaps.

**Comment by cnlklink** [comment]
Just merged this in - an error will show after the request times out.

**Comment by cnlklink** [comment]
@rneswold fixed the service end, then I noticed that we were loading the setting attribute from the reading attribute data.  My latest PR fixes that.  We appear to be getting device info properly now!
