### ISSUE TITLE
Bug: Ask the user to confirm discarding edits before throwing them away.

### ISSUE THREAD

**Issue by cnlklink** [fermi-ad/parameter_page_app#19]
Right now clicking the row delete button while in edit mode asks the user for confirmation.  That should be removed.

**Comment by rneswold** [comment]
How about, along the bottom row (in edit mode), we display these buttons:

[Cancel Changes] [Save Current] [Save and Exit]

"Save Current" would let you save all the outstanding changes and keep you in edit mode. Or is the parameter page simple enough we can simply save or cancel the whole thing?

**Comment by cnlklink** [comment]
@rneswold That's a different issue.  But I think we have that covered now as you have the Save menu command outside of the edit page workflow.

As for the issue of asking for confirmation on removal of each page entry - that's been removed.
